<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "nr_template"
 *
 * Auto generated by Extension Builder 2014-12-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
    'title' => 'NR PageTree',
    'description' => 'Provides extended functionality for the pagetree, such as showing non page records and wiring them to custom pages',
    'category' => 'backend',
    'author' => 'Christian Opitz',
    'author_email' => 'christian.opitz@netresearch.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.1',
    'constraints' => array(
        'depends' => array(
            'typo3' => "6.2.0-6.2.99"
        ),
        'conflicts' => array(
        ),
        'suggests' => array(
        ),
    ),
);
